- name: Install RPMFusion repositories
  yum: name={{ item }} state=present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-20.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-20.noarch.rpm

- name: Install Broadcom wl modules
  yum: name=kmod-wl state=present

- name: Install nonfree codecs
  yum: pkg={{ item }} state=present
  with_items:
    - gstreamer-plugins-ugly
    - gstreamer-plugins-bad
    - gstreamer-ffmpeg

- name: Install fedora-skype yum repo
  copy: src=fedora-skype.repo dest=/etc/yum.repos.d/fedora-skype.repo

- name: Install Skype and purple-skype
  yum: name={{ item }} state=present
  with_items:
    - skype
    - purple-skype

- name: Install Google Chrome yum repo
  copy: src=google-chrome.repo dest=/etc/yum.repos.d/google-chrome.repo

- name: Install Google Chrome
  yum: pkg=google-chrome-unstable state=present
